### PR TITLE
Added admin command

### PR DESCRIPTION
**Pull request by maca134**
Added admin command that returns a list of connected RCON clients.

### CODE REVIEW

**Comment by mvries** [comment]
Cool, thank you. :smile:

**Comment by maca134** [comment]
Are you the person who pushes to nuget?

**Comment by mvries** [comment]
Yes, what's up?

**Comment by maca134** [comment]
Just wondering if you can push/release a version? =D

**Comment by mvries** [comment]
Ah alright, I'll have to check how this nuget stuff works again, been almost a year since I've done anything on there. ^^

**Comment by maca134** [comment]
Nice! Thank you.

**Comment by mvries** [comment]
Should be updated, might take a couple of days to do it's thing on NuGet though.

**Pull request merged**
